model_params:
  cond: False
  in_channels: 1
  out_channels: 2
  dim: 32
  padding: 8
  kernel_list: [32, 32, 32, 32, 32]
  kernel_size_list: [1, 1, 1, 1, 1]
  padding_list: [0, 0, 0, 0, 0]
  hidden_list: [128]
  act_func: GELU
  mode_list: [32, 10]
  dropout: 0.0
  drop_path_rate: 0.0
  wave_prior: True
  wp_input_cat: True
  waveprior_concatenate: False
  freqlinear: False
  positional_encoding: False
  eps_info: False

train_params:
  optimizer_name: adamw
  optimizer_lr: 0.002
  optimizer_weight_decay: 0.0001
  criterion_name: nmse
  scheduler_name: cosine
  scheduler_lr_gamma: 0.99
  scheduler_lr_min: 0.00001

  # simulation / dataset setting.
  step: 20
  resolution: 40
  width: 0.12
  batch_size: 32
  normalize: False


run:
  device: [0]
  deterministic: True
  random_state: 42
  n_epochs: 200
  num_workers: 4
  pin_memory: True


saver:
  save_root: "checkpoints/fno2d/nmse_waveprior_32dim_5layer_3210"
dataset:
  dataset_root: "dataset/data/120nmdata"
  test_dataset_root: "dataset/data/120nmdata/ceviche_test"
  dataset_folder_name: "rand_wvl_pt"
  mode: "train"