model_params:
  in_channels: 1
  out_channels: 2
  dim: 64
  padding: 8
  kernel_list: [64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64]
  kernel_size_list: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  padding_list: [0, 0, 0, 0]
  hidden_list: [256]
  act_func: GELU
  mode_list: [50, 60]
  dropout: 0.0
  drop_path_rate: 0.0
  cond: False 
  wave_prior: True
  wp_mult: False
  positional_encoding: False
  eps_info: False
  freqlinear: False



train_params:
  optimizer_name: adamw
  optimizer_lr: 0.002
  optimizer_weight_decay: 0.0001
  criterion_name: nmse
  #### We do not use the maxwell loss.
  aux_params:
    maxwell:
      weight: 0.0
      n_sub : 1.45
      n_1 : 1.0
      n_2 : 1.4623
      c_0 : 299792458.13099605
      eps_0 : 8.85418782e-12
      mu_0 : 1.25663706e-6
  maxwell_margin: 0.00
  scheduler_name: cosine
  scheduler_lr_gamma: 0.99
  scheduler_lr_min: 0.00001
  adjoint: False
  ceviche: True
  ceviche_cond : True # inputdata : 5nm 기준 띄어서 - 10000개. test data : all.
  step: 20
  resolution: 40
  width: 0.12

  interp: True
  data_num: 10000
  batch_size: 16
  normalize: False
  without_PML: False # 2024 0515 이후 일자 데이터는 PML을 뺸 상태에서 구성했다.

run:
  device: [3]
  deterministic: True
  random_state: 42
  log_interval: 10
  n_epochs: 200
  log_root: "log"
  log_dir_name: "nmse"
  num_workers: 4
  pin_memory: True
  

plot:
  train_plot: True
  valid_plot: True
  test_plot: True
  plot_interval: 10
  plot_root: "plot"
  plot_dir_name: ""


saver:
  save_root: "checkpoints/120nm_interp_ceviche/factorfno/20step/results_checkpoint/nmse_wp_64_12layer_256_mode5060"
dataset:
  dataset_root: "dataset/data/120nmdata"
  test_dataset_root: "dataset/data/120nmdata/ceviche_test"
  dataset_folder_name: "rand_wvl_pt"
  mode: "train"

