model_params:
  in_channels: 1
  out_channels: 2
  dim: 64
  padding: 8
  kernel_list: [64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64]
  kernel_size_list: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  padding_list: [0, 0, 0, 0]
  hidden_list: [256]
  act_func: GELU
  mode_list: [50, 60]
  dropout: 0.0
  drop_path_rate: 0.0
  cond: False 
  wave_prior: False
  wp_mult: False
  positional_encoding: False
  eps_info: False
  freqlinear: True


train_params:
  optimizer_name: adamw
  optimizer_lr: 0.002
  optimizer_weight_decay: 0.0001
  criterion_name: nmse
  scheduler_name: cosine
  scheduler_lr_gamma: 0.99
  scheduler_lr_min: 0.00001

  # simulation / dataset setting.
  step: 20
  resolution: 40
  width: 0.12
  batch_size: 32
  normalize: False


run:
  device: [0]
  deterministic: True
  random_state: 42
  n_epochs: 200
  num_workers: 4
  pin_memory: True


saver:
  save_root: "checkpoints/factorfno/nmse_wp_64_12layer_256_mode5060_modulation"
dataset:
  dataset_root: "dataset/data/120nmdata"
  test_dataset_root: "dataset/data/120nmdata/ceviche_test"
  dataset_folder_name: "rand_wvl_pt"
  mode: "train"

